### ISSUE TITLE
Use of FixedBufferAllocator

### ISSUE THREAD

**Issue by pedromsilvapt** [suirad/zig-header-gen#1]
Hi, was looking into your code to use on a project of mine, and looks awesome.

I did have a question though. I've noticed that you use the `FixedBufferAllocator` in the `C_Generator.init` function to store the filename. Since `filebase` is `comptime`, why not use simply `filebase ++ ".h"`? I was thinking something like this:
```zig
comptime const filebaseext = std.fs.path.basename(src_file);
comptime const filebase = filebaseext[0 .. filebaseext.len - 4];

var file = dst_dir.createFile(filebase ++ ".h", .{}) catch
    @panic("Failed to create header file for source: " ++ src_file);
```

I'm fairly new to Zig, so maybe there is something I'm not seeing here that warrants using the allocator though. I've tried running this changes on my end and they seem to work.

Btw, this is a little offtopic but I've noticed you have a python generator in your README in the roadmap. Without making any promises, would you be interested in a PR if I made one?

**Comment by suirad** [comment]
Ahh yes I must have been sleepy when using the allocator, I must have thought it needed to be done at runtime, but if it does work at comptime, it is very much a welcome change.

As far as contributions related to the python generator(or any generator); contributions are extremely welcome. I'd happily checkout & accept a PR.

**Comment by pedromsilvapt** [comment]
Ok, nice. If I do it then, I'l open a PR. Thanks!
